# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tt1YoaY4vt1Pbn7RBY748i1b8NZ646cp
"""

pip install -q openai gradio

from openai import OpenAI

client = OpenAI(api_key="")

import gradio as gr

def predict(input, history):
    history.append({"role": "user", "content": input})

    gpt_response = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=history
    )

    response = gpt_response.choices[0].message.content

    history.append({"role": "assistant", "content": response})

    messages = [(history[i]["content"], history[i+1]["content"]) for i in range(1, len(history), 2)]

    return messages, history

with gr.Blocks() as demo:
    chatbot = gr.Chatbot(label="ChatBot")

    state = gr.State([{
        "role": "system",
        "content": "당신은 친절한 인공지능 챗봇입니다. 입력에 대해 친절하게 대답해주세요."
    }])

    with gr.Row():
        txt = gr.Textbox(show_label=False, placeholder="챗봇에게 아무거나 물어보세요")

    txt.submit(predict, [txt, state], [chatbot, state])

demo.launch(debug=True, share=True)

